### ISSUE TITLE
Setup HDFS config for local short-circuit reads

### ISSUE THREAD

**Issue by koverholt** [blaze/hdfs3#8]

**Comment by mrocklin** [comment]
This issue is still live.  I still get the warnings for short-circuit reads on the testing cluster.  Is this a setting that `hdfs3` should set or do we need to leave this to the administrator of a particular cluster?

**Comment by martindurant** [comment]
Requires system-level settings in hdfs-site.xml AND environment-level setting of LIBHDFS3_CONF to point to the same file.

**Comment by mrocklin** [comment]
Does this mean that it must be handled by the cluster administrator and that we should close this issue?  Is there any sniffing of the proper file location that we should do?  Should we turn off short circuit reads if they are not permitted?

**Comment by martindurant** [comment]
Yes, I think it's a decision for the admins, and we should make libhdfs3 as a client attempt/avoid short-circuit based on the system conf. I had the little code to guess the location of hdfs-site.xml, but we still don't have an idea of how reliable that is. In any case, setting the environment variable has to happen before importing the .so.

**Comment by koverholt** [comment]
We've made shortcircuit config the default for HDFS in Anaconda Cluster. I will add some notes to the hdfs3 docs about what config needs to be in place for shortcircuit reads.

**Comment by mrocklin** [comment]
Still getting this: `retry the same node but disable read shortcircuit feature`

**Comment by koverholt** [comment]
Could you post a snippet of code that produces the error/warning?

**Comment by mrocklin** [comment]
```python
In [2]: from distributed import Executor
In [3]: from distributed.hdfs import read, read_binary
In [4]: e = Executor("172.31.9.67:8786")

In [6]: from hdfs3 import HDFileSystem
In [7]: hdfs = HDFileSystem()

In [8]: bytes = read_binary('/nyc/trip_data_1.csv', hdfs=hdfs, delimiter=b'\r\n')
```

**Comment by mrocklin** [comment]
That's after you have a cluster set up, which I do manually with 

```
ssh-dscheduler
cssh-dworker address
```

**Comment by koverholt** [comment]
This seems to be working now after:

* Configuring the appropriate settings in hdfs-site.xml
* Setting export LIBHDFS3_CONF=/etc/hadoop/conf/hdfs-site.xml

I was able to read from a worker node with no warnings/errors.

**Comment by koverholt** [comment]
I added some notes to the docs in #35.

**Comment by mrocklin** [comment]
I'm still getting this error on the cluster.  Did we want to set this environment variable in a persistent way somehow?  Do we want hdfs3 to find this file and set the environment variable in some way?

**Comment by koverholt** [comment]
Yes, we could set `LIBHDFS3_CONF` using the file that we find here: https://github.com/blaze/hdfs3/blob/master/hdfs3/core.py#L23-L38

**Comment by martindurant** [comment]
I believe this needs to happen before importing libhdfs3.so
